export const SPEED = 100;
export const BOARD_SIZE = 625;
export const MAX_NUMBER_OF_LEADERS = 12;

export const DIRECTION_NUMERIC = {
  UP: -25,
  RIGHT: 1,
  DOWN: 25,
  LEFT: -1,
} as const;

export const CONTROL_KEYS = {
  UP: 'w',
  RIGHT: 'd',
  DOWN: 's',
  LEFT: 'a',
} as const;

export const KEYBOARD_DIRECTION = {
  [CONTROL_KEYS.UP]: DIRECTION_NUMERIC.UP,
  [CONTROL_KEYS.RIGHT]: DIRECTION_NUMERIC.RIGHT,
  [CONTROL_KEYS.DOWN]: DIRECTION_NUMERIC.DOWN,
  [CONTROL_KEYS.LEFT]: DIRECTION_NUMERIC.LEFT,
} as const;

export const STATUS = {
  START: 'START',
  GAME_IS_ON: 'GAME_IS_ON',
  ON_PAUSE: 'ON_PAUSE',
  GAME_OVER: 'GAME_OVER',
} as const;

export const LABEL = {
  [STATUS.START]: 'START THE GAME',
  [STATUS.GAME_IS_ON]: 'GAME IS ON!',
  [STATUS.ON_PAUSE]: 'ON PAUSE...',
  [STATUS.GAME_OVER]: 'GAME OVER!',
} as const;

export const MESSAGE = {
  [STATUS.START]: 'USE W, A, S, D TO START THE GAME',
  [STATUS.GAME_IS_ON]: 'USE W, A, S, D TO MOVE AROUND THE BOARD',
  [STATUS.ON_PAUSE]: 'USE W, A, S, D TO CONTINUE THE GAME',
  [STATUS.GAME_OVER]: 'PRESS START OVER TO PLAY AGAIN',
} as const;
